### PR TITLE
Fix for webpack 4

### LINKED ISSUE #25: Not working on Webpack 4
```
Cannot read property 'context' of undefined
```

### PR DESCRIPTION
**Pull request by princemaple**
according to THE guy https://twitter.com/TheLarkInn/status/968286344794419200

close #25

### CODE REVIEW

**Comment by princemaple** [comment]
Tested the change on my own project, seems to work!

**Comment by princemaple** [comment]
Hi @developit is there anything more I need to do to get this PR merged?

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Nope, looks good to me!

**Comment by princemaple** [comment]
Thanks for merging! 🎉  Could we have a new release published please?

**Comment by pkeuter** [comment]
Hi @developit. Any reason this is not released yet?

**Comment by developit** [comment]
nope! releasing now

**Comment by developit** [comment]
Released as [1.0.2](https://github.com/developit/workerize-loader/releases/tag/1.0.2)

**Comment by princemaple** [comment]
Thanks a lot!

**Comment by pkeuter** [comment]
Yeah thanks for this, ❤️ this loader!

**Pull request merged**
